"""
Environment File Manager for VibeShield
Handles .env file creation/updates and .gitignore management.
"""

import os
import re
from pathlib import Path
from typing import Optional, Tuple


class EnvManager:
    """Manages .env file operations and .gitignore updates."""
    
    def __init__(self, project_root: str):
        """
        Initialize the EnvManager.
        
        Args:
            project_root: Path to the project root directory
        """
        self.project_root = Path(project_root)
        self.env_file = self.project_root / ".env"
        self.gitignore_file = self.project_root / ".gitignore"
    
    def generate_variable_name(self, original_key: str, context: str = "") -> str:
        """
        Generate a meaningful environment variable name.
        
        Args:
            original_key: The original key string
            context: Additional context (e.g., variable name from code)
            
        Returns:
            str: Generated variable name (e.g., "OPENAI_API_KEY")
        """
        # Check for common API key prefixes
        prefixes = {
            "sk-": "OPENAI_API_KEY",
            "xkeysib-": "BREVO_API_KEY",
            "AIza": "GOOGLE_API_KEY",
            "ghp_": "GITHUB_TOKEN",
            "gho_": "GITHUB_OAUTH_TOKEN",
        }
        
        for prefix, var_name in prefixes.items():
            if original_key.startswith(prefix):
                return var_name
        
        # Try to extract from context
        if context:
            # Clean the context to make a valid env var name
            clean_context = re.sub(r'[^A-Za-z0-9_]', '_', context)
            clean_context = clean_context.upper().strip('_')
            if clean_context:
                return clean_context
        
        # Default fallback
        return "API_KEY"
    
    def add_to_env(self, var_name: str, value: str) -> bool:
        """
        Add or update a variable in the .env file.
        
        Args:
            var_name: Environment variable name
            value: Environment variable value
            
        Returns:
            bool: True if successful
        """
        try:
            # Read existing content
            existing_vars = {}
            if self.env_file.exists():
                with open(self.env_file, 'r') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#') and '=' in line:
                            key, val = line.split('=', 1)
                            existing_vars[key.strip()] = val.strip()
            
            # Add or update the variable
            existing_vars[var_name] = value
            
            # Write back to file
            with open(self.env_file, 'w') as f:
                f.write("# Environment Variables - DO NOT COMMIT THIS FILE\n")
                f.write("# Generated by VibeShield\n\n")
                for key, val in existing_vars.items():
                    f.write(f"{key}={val}\n")
            
            return True
        except Exception as e:
            print(f"Error adding to .env: {e}")
            return False
    
    def update_gitignore(self) -> bool:
        """
        Ensure .env is in .gitignore.
        
        Returns:
            bool: True if successful
        """
        try:
            gitignore_content = []
            env_exists = False
            
            # Read existing .gitignore
            if self.gitignore_file.exists():
                with open(self.gitignore_file, 'r') as f:
                    gitignore_content = f.readlines()
                    
                # Check if .env is already there
                for line in gitignore_content:
                    if line.strip() in ['.env', '*.env', '.env*']:
                        env_exists = True
                        break
            
            # Add .env if not present
            if not env_exists:
                if gitignore_content and not gitignore_content[-1].endswith('\n'):
                    gitignore_content.append('\n')
                
                gitignore_content.append('\n# Environment variables (added by VibeShield)\n')
                gitignore_content.append('.env\n')
                
                with open(self.gitignore_file, 'w') as f:
                    f.writelines(gitignore_content)
            
            return True
        except Exception as e:
            print(f"Error updating .gitignore: {e}")
            return False
    
    def get_env_reference(self, var_name: str, language: str = "javascript") -> str:
        """
        Get the code reference for accessing the environment variable.
        
        Args:
            var_name: Environment variable name
            language: Programming language (javascript, python, etc.)
            
        Returns:
            str: Code to access the environment variable
        """
        references = {
            "javascript": f"process.env.{var_name}",
            "typescript": f"process.env.{var_name}",
            "python": f"os.environ.get('{var_name}')",
            "dart": f"dotenv.env['{var_name}']",
        }
        
        return references.get(language.lower(), f"process.env.{var_name}")


if __name__ == "__main__":
    # Test the EnvManager
    import tempfile
    import shutil
    
    # Create a temporary directory for testing
    test_dir = tempfile.mkdtemp()
    print(f"Testing in: {test_dir}")
    
    try:
        manager = EnvManager(test_dir)
        
        # Test variable name generation
        print("\n1. Testing variable name generation:")
        print(f"   sk- prefix -> {manager.generate_variable_name('sk-1234')}")
        print(f"   xkeysib- prefix -> {manager.generate_variable_name('xkeysib-abc')}")
        
        # Test adding to .env
        print("\n2. Adding to .env file:")
        manager.add_to_env("OPENAI_API_KEY", "sk-test-key-here")
        manager.add_to_env("BREVO_API_KEY", "xkeysib-another-key")
        
        with open(manager.env_file, 'r') as f:
            print("   .env contents:")
            print("   " + "\n   ".join(f.readlines()))
        
        # Test .gitignore update
        print("\n3. Updating .gitignore:")
        manager.update_gitignore()
        
        if manager.gitignore_file.exists():
            with open(manager.gitignore_file, 'r') as f:
                print("   .gitignore contents:")
                print("   " + "\n   ".join(f.readlines()))
        
        # Test code reference generation
        print("\n4. Code references:")
        print(f"   JavaScript: {manager.get_env_reference('OPENAI_API_KEY', 'javascript')}")
        print(f"   Python: {manager.get_env_reference('OPENAI_API_KEY', 'python')}")
        
    finally:
        # Clean up
        shutil.rmtree(test_dir)
        print(f"\nCleaned up test directory")